/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_lspmessage_2eproto__INCLUDED
#define PROTOBUF_C_lspmessage_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _LSPMessage LSPMessage;


/* --- enums --- */


/* --- messages --- */

struct  _LSPMessage
{
  ProtobufCMessage base;
  uint32_t connid;
  uint32_t seqnum;
  ProtobufCBinaryData payload;
};
#define LSPMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lspmessage__descriptor) \
    , 0, 0, {0,NULL} }


/* LSPMessage methods */
void   lspmessage__init
                     (LSPMessage         *message);
size_t lspmessage__get_packed_size
                     (const LSPMessage   *message);
size_t lspmessage__pack
                     (const LSPMessage   *message,
                      uint8_t             *out);
size_t lspmessage__pack_to_buffer
                     (const LSPMessage   *message,
                      ProtobufCBuffer     *buffer);
LSPMessage *
       lspmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lspmessage__free_unpacked
                     (LSPMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LSPMessage_Closure)
                 (const LSPMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor lspmessage__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_lspmessage_2eproto__INCLUDED */
